### ISSUE TITLE
Issues for JOSS

### ISSUE THREAD

**Issue by Fil** [mirzaevinom/egtplot#2]
Review for JOSS (https://github.com/openjournals/joss-reviews/issues/735)

- **Installation**

I struggled to install the package on anaconda/macos, but finally managed to install everything on a docker container and the notebook is now running smoothly in jupyter lab.

I used:
```
pip install matplotlib scipy shapely imageio moviepy tqdm jupyter
```

I then added `pip install requests` to make the movie export work. But for some reason it still gets stuck at 99%
```
[MoviePy] Building file animation_2.gif with imageio
 99%|█████████▉| 120/121 [00:05<00:00, 21.12it/s]
```

other than that, it seems to work fine, creating the expected diagrams.

It would be good to make sure installation is easier — maybe a complete Dockerfile could help some users.

Regarding:
- ** A statement of need **: it is clear in the paper, but not in the README.md
- ** Automated tests** . and ** Community guidelines** would be welcome

**Comment by drew-williamson** [comment]
Thank you @Fil for the comments. We have created a docker container located at https://hub.docker.com/r/drewfkw/egtplot/ to ease installation. Sorry yours was so troublesome!

A statement of need has been added to `README.md`, automated tests have been added in the file `test_egtplot.py`, and community guidelines have been added as a section to `README.md` entitled "Contributing and Issues."

**Comment by Fil** [comment]
The docker image installs nicely, and the demo notebook is easy to find - thanks a lot for this.

The demo notebook runs well, but it stops at the exact same spot as it did on my <del>local</del> <ins>own docker</ins> installation. 
<img width="655" alt="capture d ecran 2018-05-29 a 21 40 30" src="https://user-images.githubusercontent.com/7001/40681339-277fa1b8-6389-11e8-99bc-7db4cf50a904.png">

However I now understand 💡 that the kernel has probably saved the gif somewhere on disk — it just doesn't show up where it's supposed to, in the next cell (and I was troubled by 120/121 which seems incomplete… but the cell had finished).

And, applying the `animation.ipython_display(fps=fps, loop=True, autoplay=True)` command suggested a few lines later works perfectly.

Once this is resolved (in any way you wish), I'm good.

**Comment by drew-williamson** [comment]
We have fixed the gif loading error. The issue was simply a lack of a . before /images in the html loading the gifs. Not sure why tqdm stops at 99% and 120/121 though the cell finishes running--very strange.

Thanks!
